name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: read
      id-token: write  # Grant permission for ID token generation

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build --if-present

    # Upload the build artifact for deployment
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages-dist  # Artifact name should match the one used in deploy-pages
        path: ./dist  # Path to the build output directory

    - name: Run Tests
      run: npm test  # Ensure you have a test script in package.json

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: "github-pages-dist"  # Should match the artifact name in upload
        preview: false
