name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: read
      id-token: write  # For OIDC token
      pages: write     # Add the pages: write permission here

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build --if-present

    # Upload the build artifact for deployment
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages-dist
        path: ./dist  # Adjust the path if necessary

  deploy:
    needs: build
    runs-on: self-hosted

    permissions:
      id-token: write   # Keep this for OIDC token
      pages: write      # Add pages: write permission for deploy

    environment:
      name: github-pages  # Specify the environment name here

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: "github-pages-dist"  # Ensure this matches the uploaded artifact name
        preview: false
